baseURL = 'https://prathamvy.github.io/'
languageCode = 'en-us'
title = 'Pratham Yashwante'
theme = 'archie'

[params]
  mode = "toggle"
  subtitle = "MS CS Student at UC San Diego"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/prathamvy"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/prathamyashwante"

[[params.social]]
  name = "Google Scholar"
  icon = "book"
  url = "https://scholar.google.com/citations?user=l7KzSbgAAAAJ&hl=en"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:prathamyashwantepy@gmail.com"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2